name: check-server

on:
  push:
    paths-ignore:
      - '**/*.md'
  pull_request:
    paths-ignore:
      - '**/*.md'
jobs:
  run:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          token: ${{ secrets.BYTELEGENDBOT_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache node modules
        uses: actions/cache@v1
        env:
          cache-name: cache-gradle-user-home
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Show Gradle version
        run: ./gradlew --version
      - name: Build with Gradle
        run: ./gradlew check --scan
        env:
          AWS_DEFAULT_REGION: cn-north-1
          AWS_ACCESS_KEY_ID: dummy
          AWS_SECRET_ACCESS_KEY: dummy
